services:
  redis:
    image: redis:7-alpine
    restart: always

  consumer:
    build:
      context: .
      dockerfile: apps/consumer/dockerfile
    env_file:
      - apps/consumer/.env.test
    volumes:
      - ./apps/consumer:/app/apps/consumer
      - ./libs:/app/libs
      - ./logs/consumer:/var/log/consumer
    ports:
      - ${CONSUMER_EXPOSED_PORT}:3000 # right-side port must be in sync with the PORT value in apps/consumer/.env
    depends_on:
      - redis
    entrypoint: >
      sh -c "npm run test:int --detectOpenHandles
      | tee /var/log/consumer/integrationTests.log"

  producer:
    build:
      context: .
      dockerfile: apps/producer/dockerfile
    env_file:
      - apps/producer/.env.test
    volumes:
      - ./apps/producer:/app/apps/producer
      - ./libs:/app/libs
      - ./logs/producer:/var/log/producer
    entrypoint: >
      sh -c "npm run test:int --detectOpenHandles
      | tee /var/log/producer/integrationTests.log"
