services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'
    restart: always

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    restart: always
    volumes:
      - redis-data:/data

  base:
    build:
      context: .
      dockerfile: dockerfile
    image: base

  producer:
    build:
      context: .
      dockerfile: apps/producer/dockerfile
    volumes:
      - ./apps/producer:/app/apps/producer
      - ./node_modules:/app/node_modules
      - ./libs:/app/libs
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
    depends_on:
      - base
      - rabbitmq

  consumer:
    build:
      context: .
      dockerfile: apps/consumer/dockerfile
    volumes:
      - ./apps/consumer:/app/apps/consumer
      - ./node_modules:/app/node_modules
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./libs:/app/libs
    depends_on:
      - base
      - rabbitmq
      - redis
    ports:
      - '3000:3000' # host:container

volumes:
  redis-data:
