services:
  base:
    build:
      context: .
      dockerfile: dockerfile
    image: base

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'
    restart: always

  producer:
    build:
      context: .
      dockerfile: apps/producer/dockerfile
    volumes:
      - ./apps/producer:/app/apps/producer
      - ./node_modules:/app/node_modules
      - ./libs:/app/libs
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
    depends_on:
      - base
      - rabbitmq

  consumer:
    build:
      context: .
      dockerfile: apps/consumer/dockerfile
    volumes:
      - ./apps/consumer:/app/apps/consumer
      - ./node_modules:/app/node_modules
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./libs:/app/libs
    depends_on:
      - base
      - rabbitmq
