services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=${RMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RMQ_PWD}

  redis:
    image: redis:7-alpine
    restart: always
    volumes:
      - redis-data:/data

  base:
    build:
      context: .
      dockerfile: dockerfile
    image: base

  producer:
    build:
      context: .
      dockerfile: apps/producer/dockerfile
    env_file:
      - apps/producer/.env
    volumes:
      - ./apps/producer:/app/apps/producer
      - ./node_modules:/app/node_modules
      - ./libs:/app/libs
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
    depends_on:
      - base
      - rabbitmq

  consumer:
    build:
      context: .
      dockerfile: apps/consumer/dockerfile
    env_file:
      - apps/producer/.env
    volumes:
      - ./apps/consumer:/app/apps/consumer
      - ./node_modules:/app/node_modules
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./libs:/app/libs
    ports:
      - ${CONSUMER_EXPOSED_PORT}:3000 # right-side port must be in sync with the PORT value in apps/consumer/.env
    depends_on:
      - base
      - rabbitmq
      - redis

volumes:
  redis-data:
